name: Test Ubuntu24.04 CI helpers
run-name: Ubuntu24.04 helper test - ${{ inputs.custom_repo_commit_hash }}

on:
  workflow_dispatch:
    inputs:
      custom_repo:
        description: Repository containing the image templates
        required: true
        type: string
      custom_repo_commit_hash:
        description: Commit containing the image templates
        required: true
        type: string
      pr_title:
        description: Display title for the remote CI run
        required: true
        type: string

jobs:
  test:
    uses: ./.github/workflows/trigger-ubuntu-win-build.yml
    with:
      image_type: ubuntu2404
      custom_repo: ${{ inputs.custom_repo }}
      custom_repo_commit_hash: ${{ inputs.custom_repo_commit_hash }}
      pr_title: ${{ inputs.pr_title }}
    secrets: inherit